### PR TITLE
Working on features

### PR DESCRIPTION
**Pull request by benrosenthal**

### CODE REVIEW

**Comment by drew-mahrt** [comment]
#  RUBRIC
**Project 4 | ADI** 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Build a complete application | | x |  |
| Have an impressive design and user experience | | | x |
| Use at least one API or SDK | | | x | 
| Implement thoughtful user stores |  |  | x  |
| Be object oriented | | | x |
| Be robust and handle cases of failure well | | x  |  |
| Be available on the Goole Play store | x | |  |


Notes:

Overall, good job! I definitely see some potential in this app, and it has some really cool features. I like the Firebase login and S3 usage, impressive stuff.


Some problems I noticed:

- The app's name needs to be changed, and icon shouldn't be the default Android icon
- It seems like the settings menu doesn't do anything, did you mean to leave it in? Also, the logout and share options don't work.
- The layout for the screen where you add a problem is broken in landscape. The Camera, Gallery, and Done buttons don't show.
- Pictures for the posts don't show up (maybe you aren't storing in or retrieving from S3 correctly?)
- It lets me post an event without filling out any information, you need some checks before the event can be submitted
- Is there any way for me to change my password?
- **Why is Gaurav Kaushik in your commit history?**
- I know we talked about your user stories, but I can't seem to find any of your research or user story documentation

---

## Score:
Based on the requirements, you can earn a maximum of  **14**  points on this project.

#### Your total score is: **10**

**Comment by drew-mahrt** [comment]
Before I approve the final grade on the project, I need to know who Gaurav Kaushik is. Please let me know asap.

**Comment by benrosenthal** [comment]
Hey Drew,

Hope you're doing well!

Guarav Kaushik is an Android developer, whom I connected with on Chegg.com
because of his vetted profile as a tutor. We worked together privately, and
while I wrote the code for this app, Guarav helped me with general
debugging and talked me through some of the more difficult technical
problems I ran into.

As per Github, I got confused with how we were committing changes and
coordinating on Github, and I think this is why the repo log looks the way
it does.

Let me know if you need any other information!

BenRosenthal

**Comment by drew-mahrt** [comment]
Sounds good. I went ahead and let outcomes know that you're all set to start working with them again.

**Pull request closed without merging**
